name: Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  Pipeline:
    name: QA Pipeline
    strategy:
      matrix:
        node-version: [12.x]

    runs-on: ubuntu-latest
    steps:
      - name: Use Node
        uses: actions/checkout@v2

      - name: Checkout Code
        uses: actions/setup-node@v1

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn

      - name: Audit Dependencies
        run: yarn audit

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test
